#ifndef GUARD_CONSTANTS_BATTLE_TRANSITION_H
#define GUARD_CONSTANTS_BATTLE_TRANSITION_H

#define MUGSHOT_SIDNEY      0
#define MUGSHOT_PHOEBE      1
#define MUGSHOT_GLACIA      2
#define MUGSHOT_DRAKE       3
#define MUGSHOT_CHAMPION    4
#define MUGSHOT_RED         5
#define MUGSHOT_LEAF 				6
#define MUGSHOT_BLUE 				7
#define MUGSHOT_HENRY       8
#define MUGSHOT_ROXANNE     9
#define MUGSHOT_BRAWLY      10
#define MUGSHOT_WATTSON     11
#define MUGSHOT_FLANNERY    12
#define MUGSHOT_NORMAN      13
#define MUGSHOT_WINONA      14
#define MUGSHOT_TATE_AND_LIZA 15
#define MUGSHOT_WALLACE     16
#define MUGSHOTS_COUNT      17

#endif //GUARD_CONSTANTS_BATTLE_TRANSITION_H
